services:
  storage:
    image: bitnami/minio:2023.3.24
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio_user
      MINIO_ROOT_PASSWORD: minio_password
    networks:
      - locale-network
  postgres_db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cloud_service
    networks:
      - locale-network
  cloud_service:
    build: .
    restart: always
    ports:
      - 8888:8888
    environment:
      DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/cloud_service
      DATASOURCE_USER: user
      DATASOURCE_PASS: password
      MINIO_USER: minio_user
      MINIO_PASSWORD: minio_password
      MINIO_URL: http://storage:9000
      TOKEN_SECRET: secret
      TOKEN_VALIDITY: 15
    networks:
      - locale-network
networks:
  locale-network:
    driver: bridge